added "restart" option to openstack-admin

diff --git a/scripts/openstack-admin b/scripts/openstack-admin
--- a/scripts/openstack-admin
+++ b/scripts/openstack-admin
@@ -20,43 +20,40 @@ setenforce permissive
 # Head controller node hostname
 CONTROLLER=stor01.osop.rhcloud.com
 
-# Public physical interface
-PUB_NIC=eth4
-
-# Private physical interface
-PRIV_NIC=eth5
-
-# Nova internal virtual network name and range
-VIRT_NET_NAME=osop-virt
-VIRT_NET_NET=192.168.179.0
-VIRT_NET_MASK=24
-
-if [ -z $VIRT_NET_NAME ]; then
-    echo "VIRT_NET_NAME not set.  Please set it.  Aborting..."
-    exit 1
-fi
-
-# Public/Floating network name and range
+# Public/Floating network settings
 
 PUB_NET_NAME=osop-pub
 PUB_NET_NIC=eth4
 PUB_NET_NET=209.132.179.0
 PUB_NET_MASK=24
 
-if [ -z $VIRT_NET_NAME ]; then
-    echo "VIRT_NET_NAME not set.  Please set it.  Aborting..."
+if [ -z $PUB_NET_NAME ]; then
+    echo "PUB_NET_NAME not set.  Please set it.  Aborting..."
     exit 1
 fi
 
-# Flat, Private network name and range
+# Flat, Private network settings
 
 PRIV_NET_NAME=osop-priv
 PRIV_NET_NIC=eth5
+PRIV_NET_BRIDGE=br5
 PRIV_NET_NET=10.4.59.0
 PRIV_NET_MASK=24
 
 if [ -z $PRIV_NET_NAME ]; then
     echo "PRIV_NET_NAME not set.  Please set it.  Aborting..."
+    exit 1
+fi
+
+# Nova internal, virtual network settings
+
+VIRT_NET_NAME=osop-virt
+VIRT_NET_BRIDGE=${VIRT_NET_NAME}br
+VIRT_NET_NET=192.168.179.0
+VIRT_NET_MASK=24
+
+if [ -z $VIRT_NET_NAME ]; then
+    echo "VIRT_NET_NAME not set.  Please set it.  Aborting..."
     exit 1
 fi
 
@@ -84,6 +81,28 @@ if [ $? -eq 1 ]; then
     echo "Something failed.  Aborting..."
     exit 1
 fi
+}
+
+controller_iptables_config() {
+
+    # Open the MySQL ports for the local network, only
+    iptables -I INPUT 2 -s ${VIRT_NET_NET}/${VIRT_NET_MASK} -p tcp -m tcp --dport 3306 -j ACCEPT 
+    iptables -I INPUT 3 -s ${PUB_NET_NET}/${PUB_NET_MASK} -p tcp -m tcp --dport 3306 -j ACCEPT 
+    iptables -I INPUT 4 -s ${PRIV_NET_NET}/${PRIV_NET_MASK} -p tcp -m tcp --dport 3306 -j ACCEPT 
+    # Open httpd 
+    iptables -I INPUT 5 -p tcp -m tcp --dport 80 -j ACCEPT 
+    # Open the port for VNC
+    iptables -I INPUT 6 -p tcp -m tcp --dport 6080 -j ACCEPT 
+    # Open the Keystone port for the local networks, only
+    iptables -I INPUT 7 -s ${VIRT_NET_NET}/${VIRT_NET_MASK} -p tcp -m tcp --dport 5000 -j ACCEPT 
+    iptables -I INPUT 7 -s ${PUB_NET_NET}/${PUB_NET_MASK} -p tcp -m tcp --dport 5000 -j ACCEPT 
+    iptables -I INPUT 7 -s ${PRIV_NET_NET}/${PRIV_NET_MASK} -p tcp -m tcp --dport 5000 -j ACCEPT 
+}
+
+compute_iptables_config() {
+
+    # Open the port for VNC
+    iptables -I INPUT 2 -p tcp -m tcp --dport 6080 -j ACCEPT 
 }
 
 # Install EPEL yum repo
@@ -144,7 +163,6 @@ done
 
 # Open the port for nova-client
 
-iptables -I INPUT 6 -p tcp -m tcp --dport 5000 -j ACCEPT 
 }
 
 controller_install_basics() {
@@ -157,11 +175,6 @@ openstack-db --service nova --init
 check_it
 openstack-db --service glance --init
 check_it
-
-# Open the MySQL ports for the local network, only
-iptables -I INPUT 1 -s ${VIRT_NET_NET}/${VIRT_NET_MASK} -p tcp -m tcp --dport 3306 -j ACCEPT 
-iptables -I INPUT 2 -s ${PUB_NET_NET}/${PUB_NET_MASK} -p tcp -m tcp --dport 3306 -j ACCEPT 
-iptables -I INPUT 3 -s ${PRIV_NET_NET}/${PRIV_NET_MASK} -p tcp -m tcp --dport 3306 -j ACCEPT 
 
 # Enable and Start services
 for svc in qpidd libvirtd openstack-glance-api openstack-glance-registry
@@ -251,7 +264,7 @@ nova_network_config() {
 
 source_keystonerc
 
-nova-manage network create $VIRT_NET_NAME ${VIRT_NET_NET}/${VIRT_NET_MASK} 1 256 --bridge=${VIRT_NET_NAME}br --bridge_interface=${PRIV_NIC}
+nova-manage network create $VIRT_NET_NAME ${VIRT_NET_NET}/${VIRT_NET_MASK} 1 256 --bridge=${VIRT_NET_BRIDGE} --bridge_interface=${PRIV_NET_NIC}
 nova-manage network list
 check_it
 
@@ -263,7 +276,13 @@ nova floating-ip-list
 check_it
 
 # Add the virtual bridge for compute nodes
-openstack-config --set /etc/nova/nova.conf DEFAULT flat_interface ${PRIV_NIC}
+openstack-config --set /etc/nova/nova.conf DEFAULT flat_interface ${PRIV_NET_NIC}
+
+
+# Modify security groups to allow ssh and icmp
+
+    nova secgroup-add-rule default tcp 22 22 ${VIRT_NET_NET}/0
+    nova secgroup-add-rule default icmp -1 -1 ${VIRT_NET_NET}/0
 }
 
 # Register a test image to run
@@ -333,7 +352,6 @@ yum -y -q install openstack-dashboard
 chkconfig httpd on
 service httpd restart
 setsebool -P httpd_can_network_connect=on
-iptables -I INPUT 4 -p tcp -m tcp --dport 80 -j ACCEPT 
 
 }
 
@@ -514,9 +532,6 @@ euca-describe-instances
 euca-get-console-output i-00000001
 euca-terminate-instances i-00000001
 
-# Open the port for euca auth
-
-# iptables -I INPUT 6 -p tcp -m tcp --dport 5000 -j ACCEPT 
 
 }
 
@@ -575,7 +590,7 @@ image_add_ip() {
 
 source_keystonerc
 
-#euca# openstack-config --set /etc/nova/nova.conf DEFAULT public_interface ${PUB_NIC}
+#euca# openstack-config --set /etc/nova/nova.conf DEFAULT public_interface ${PUB_NET_NIC}
 #euca# service openstack-nova-network restart
 
 VM_IP=`nova list | grep $PUB_NET_NAME | awk -F"$PUB_NET_NAME=" '{print $2}' | awk '{print $1}'`
@@ -609,17 +624,14 @@ source_keystonerc
     yum -y -q install openstack-nova-novncproxy
 
 # Enable VNC in the controller
-    echo "# Adding VNC support
-novncproxy_host = 0.0.0.0
-novncproxy_port = 6080
-novncproxy_base_url=http://${CONTROLLER}:6080/vnc_auto.html
-vnc_enabled=true
-vncserver_listen=127.0.0.1
-vncserver_proxyclient_address=127.0.0.1" >> /etc/nova/nova.conf
+#     echo "# Adding VNC support
+# novncproxy_host = 0.0.0.0
+# novncproxy_port = 6080
+# novncproxy_base_url=http://${CONTROLLER}:6080/vnc_auto.html
+# vnc_enabled=true
+# vncserver_listen=127.0.0.1
+# vncserver_proxyclient_address=127.0.0.1" >> /etc/nova/nova.conf
 
-# Open the port for VNC
-
-iptables -I INPUT 5 -p tcp -m tcp --dport 6080 -j ACCEPT 
 
 # Restart the services
 for svc in consoleauth novncproxy compute
@@ -632,11 +644,11 @@ done
 
 compute_vnc_install_config() {
     yum -y -q install openstack-nova-novncproxy
-    echo "# Adding VNC support
-novncproxy_base_url=http://${CONTROLLER}:6080/vnc_auto.html
-vnc_enabled=true
-vncserver_listen=`hostname`
-vncserver_proxyclient_address=`hostname`" >> /etc/nova/nova.conf
+#    echo "# Adding VNC support
+#novncproxy_base_url=http://${CONTROLLER}:6080/vnc_auto.html
+#vnc_enabled=true
+#vncserver_listen=`hostname`
+#vncserver_proxyclient_address=`hostname`" >> /etc/nova/nova.conf
 
 # Restart the services
 for svc in consoleauth novncproxy
@@ -700,31 +712,37 @@ enable_ntp() {
 }
 
 compute_install_basics() {
-    yum -y -q install openstack-nova openstack-nova-compute openstack-nova-network openstack-nova-api dnsmasq-utils policycoreutils-python
+    yum -y -q install openstack-nova openstack-nova-compute openstack-nova-network openstack-nova-api python-keystone openstack-utils dnsmasq-utils policycoreutils-python
     chkconfig libvirtd on
     service libvirtd start
     setenforce 0
 
 # Configure nova to find the services on the controller
-    openstack-config --set /etc/nova/nova.conf DEFAULT qpid_hostname $CONTROLLER
-    openstack-config --set /etc/nova/nova.conf DEFAULT sql_connection mysql://nova:nova@${CONTROLLER}/nova
-    openstack-config --set /etc/nova/nova.conf DEFAULT glance_api_servers ${CONTROLLER}:9292
-    openstack-config --set /etc/nova/nova.conf DEFAULT iscsi_ip_prefix ${CONTROLLER_IP}
-    openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
 
-# Configure the network interfaces
-    openstack-config --set /etc/nova/nova.conf DEFAULT flat_network_bridge ${VIRT_NET_NAME}br
-    openstack-config --set /etc/nova/nova.conf DEFAULT flat_interface ${PRIV_NIC}
+    scp root@${CONTROLLER}:/etc/nova/nova.conf /etc/nova/
+#    scp root@${CONTROLLER}:/etc/nova/api-paste.ini /etc/nova/
+
+openstack-config --set /etc/nova/nova.conf DEFAULT my_ip `ifconfig ${PRIV_NET_BRIDGE} | grep "inet addr" | awk -F"[ :]" '{print $13}'`
+
+#    openstack-config --set /etc/nova/nova.conf DEFAULT qpid_hostname $CONTROLLER
+#    openstack-config --set /etc/nova/nova.conf DEFAULT sql_connection mysql://nova:nova@${CONTROLLER}/nova
+#    openstack-config --set /etc/nova/nova.conf DEFAULT glance_api_servers ${CONTROLLER}:9292
+#    openstack-config --set /etc/nova/nova.conf DEFAULT iscsi_ip_prefix ${CONTROLLER_IP}
+#    openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
+#
+## Configure the network interfaces
+#    openstack-config --set /etc/nova/nova.conf DEFAULT flat_network_bridge ${VIRT_NET_BRIDGE}
+#    openstack-config --set /etc/nova/nova.conf DEFAULT flat_interface ${PRIV_NET_NIC}
 
 # Enable the compute service
-    for svc in compute network api
+    for svc in compute network metadata-api
     do 
         chkconfig openstack-nova-$svc on
         service openstack-nova-$svc start
     done
 
 # Configure the physical bridge interface
-#    nova-manage network create $VIRT_NET_NAME ${VIRT_NET_NET}/${VIRT_NET_MASK} --bridge=${VIRT_NET_NAME}br --bridge_interface=${PRIV_NIC}
+#    nova-manage network create $VIRT_NET_NAME ${VIRT_NET_NET}/${VIRT_NET_MASK} --bridge=${VIRT_NET_BRIDGE} --bridge_interface=${PRIV_NET_NIC}
 }
 
 
@@ -894,6 +912,22 @@ clean_openstack() {
     rm -rf keystone nova swift glance
 }
 
+restart_openstack() {
+    cd /etc/rc3.d/; 
+    for svc in `ls S*open* S*iptables` ; 
+    do 
+        ./$svc stop; 
+    done; 
+
+    /etc/init.d/dnsmasq stop; 
+    
+    for svc in `ls S*open* S*iptables` ; 
+    do 
+        ./$svc start; 
+    done; 
+    cd -
+}
+
 source_keystonerc() {
 # If ~/.keystonerc exists, source it
 if [ -e ~/.keystonerc ]; then
@@ -906,6 +940,7 @@ fi
 controller_install() {
 
     #install_epel_repo
+    controller_iptables_config
     enable_ntp
     keystone_install_config
     controller_install_basics
@@ -930,6 +965,7 @@ controller_install() {
 
 compute_install() {
     #install_epel_repo
+    compute_iptables_config
     enable_ntp
     compute_install_basics
     compute_vnc_install_config
@@ -942,6 +978,9 @@ compute_install() {
 # Install on the controller
 
 case $1 in
+    restart)
+           restart_openstack
+           ;;
     clean)
            clean_openstack
            ;;
@@ -951,10 +990,10 @@ case $1 in
            elif [ "$2" = "compute" ]; then
                  compute_install
            else
-                 echo $"$0: Usage: [ clean ] [ install {controller|compute} ]"
+                 echo $"$0: Usage: [ restart ] [ clean ] [ install {controller|compute} ]"
            fi
            ;;
-    *)    echo $"$0: Usage: [ clean ] [ install {controller|compute} ]"
+    *)    echo $"$0: Usage: [ restart ] [ clean ] [ install {controller|compute} ]"
            exit 1
            ;;
 esac
